---
{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "helm-ipfs-cluster.fullname" . }}-public
  labels:
    {{- include "helm-ipfs-cluster.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.hosts }}
    - {{ . | quote }}
  {{- end }}
  gateways:
  {{- range .Values.istio.gateways }}
    - {{ . | quote }}
  {{- end }}
  http:
    - match:
        - uri:
            prefix: /ipfs/
      route:
        - destination:
            host: {{ include "helm-ipfs-cluster.ipfs-name" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ipns/
      route:
        - destination:
            host: {{ include "helm-ipfs-cluster.ipfs-name" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: /api/v0/
      route:
        - destination:
            host: {{ include "helm-ipfs-cluster.ipfs-name" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 5001
    - match:
        - uri:
            prefix: /webui
      route:
        - destination:
            host: {{ include "helm-ipfs-cluster.ipfs-name" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 5001

    {{- if .Values.istio.exposeClusterApiPublicly }}
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "helm-ipfs-cluster.name" . }}-cluster.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 9094
    {{- else }}
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "helm-ipfs-cluster.ipfs-name" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8080
    {{- end }}
{{- end }}


---
{{- if and .Values.istio.enabled .Values.istio.adminEnabled (not .Values.istio.exposeClusterApiPublicly) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "helm-ipfs-cluster.fullname" . }}-admin
  labels:
    {{- include "helm-ipfs-cluster.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.adminHosts }}
    - {{ . | quote }}
  {{- end }}
  gateways:
  {{- range .Values.istio.adminGateways }}
    - {{ . | quote }}
  {{- end }}
  http:
    - match:
        - uri:
            exact: /
      redirect:
        uri: /id
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "helm-ipfs-cluster.name" . }}-cluster.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 9094
{{- end }}
